version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: baneservice
      POSTGRES_USER: baneserviceadmin
      POSTGRES_PASSWORD: rT038qEVTSGt  # Replace with a secure password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
