# Generated by Django 5.1.2 on 2024-10-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=10)),
                ('issue_name', models.CharField(max_length=255)),
                ('aim', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('total_credits_available', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AuditCriteria',
        ),
        migrations.AddField(
            model_name='assessmentcriteria',
            name='assessment_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload_app.assessmentissue'),
        ),
        migrations.AddField(
            model_name='assessmentissue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_upload_app.category'),
        ),
    ]
